import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import Header from "@/components/header/Header";
import { ThemeProvider } from "@/components/ui/theme-provider";

export const metadata: Metadata = {
  title: { template: "%s | Misoc", default: "Home | Misoc" },
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className={`antialiased`}>
          <Header />
          <main className="mx-auto max-w-7xl px-3 py-4 sm:px-6 sm:py-6 lg:px-8">
            {children}
          </main>
          <Toaster
            toastOptions={{
              success: { duration: 3000 },
              error: { duration: 5000 },
              style: {
                padding: "16px 24px",
                fontSize: "14px",
                textAlign: "center",
                maxWidth: "500px",
              },
            }}
          />
        </body>
      </ThemeProvider>
    </html>
  );
};

export default RootLayout;
